### ISSUE TITLE
FEATURE REQUEST: Private lobby

### ISSUE THREAD

**Issue by tunaflsh** [VisualError/Better-Lobbies#1]
Is the feature "Join lobby via code" make a private room, where only people with the code can join, or is it just for convenience and everybody can join if they find the lobby in the public list?

**Comment by VisualError** [comment]
Anybody can join any lobby even if its set as friends only if you give them the lobby code.

**Comment by VisualError** [comment]
This may be what you're looking for by the way. https://thunderstore.io/c/lethal-company/p/Dev1A3/LobbyInviteOnly/

I'll be closing this issue

**Comment by tunaflsh** [comment]
No, no. The use case you described earlier was what I was looking. This lets streamers host lobbies without the need for people to be friends with them. Appreciate your response.
