### ISSUE TITLE
[Issue] The prompt message will be overwritten and disappear, pretty sure this mod override some UI

### ISSUE THREAD

**Issue by CoolLKKPS** [VisualError/Better-Lobbies#10]
same as topic

**Comment by VisualError** [comment]
Any.. examples?

**Comment by CoolLKKPS** [comment]
"The Host Disconnected" message

**Comment by CoolLKKPS** [comment]
most error message when quit to menu

**Comment by VisualError** [comment]
This issue should hopefully be fixed in v1.1.1 release! You can manually close this issue once I release the patch and if everything is working fine :)

**Comment by CoolLKKPS** [comment]
ok will test this mod later! i just waked up >;)

**Comment by CoolLKKPS** [comment]
yep, after a few hours test, all fine now!
