### ISSUE TITLE
[BUG] Host not accept the connection when after the first game

### ISSUE THREAD

**Issue by CoolLKKPS** [VisualError/Better-Lobbies#11]
this issue previously in here:
https://github.com/TIRTAGT/LCDirectLAN/issues/2

that really took so long to figure it out... really thx for him, otherwise i will still struggling for this issue

**Comment by VisualError** [comment]
Just read the whole thing, thank you both for going through this incompatibility issue lol.

I can't believe I had this piece of code *go through release*. I'll be removing this patch thanks!
```cs
[HarmonyPatch(typeof(StartOfRound), nameof(StartOfRound.OnDisable))]
[HarmonyPostfix]
static void DisconnectOnDisable()
{
	GameNetworkManager.Instance.Disconnect(); // weeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee
}
```
