### ISSUE TITLE
BUG REPORT (V.47): Challenge moons not working on server list

### ISSUE THREAD

**Issue by DeCat4** [VisualError/Better-Lobbies#2]
Servers that have challenge moons enabled either don't show up or are not separately colored on the server list

And when searching for tags and no results are given the Text's position is bugged and it's either more to the left or just isn't there, not a big issue but it might mean future issues will come from whatever causes this.

**Comment by VisualError** [comment]
All fixed in the latest version!

**Comment by VisualError** [comment]
![image](https://github.com/VisualError/Better-Lobbies/assets/28821360/013955cd-eff8-4f0b-a2f0-6db45c4b448a)
