### ISSUE TITLE
Missing important files in repository

### ISSUE THREAD

**Issue by Nyxchrono** [VisualError/Better-Lobbies#6]
Hello, I've forked your repository in hopes of maybe making a PR but noticed that I am unable to load your project in my IDE (and build + test changes) because the repository is missing the `.csproj` and `.sln` for this plugin.

If you could change your `.gitignore` so that way the `.sln` and the `.csproj` are no longer ignored, it would be greatly appreciated.

**Comment by VisualError** [comment]
I've removed these files in .gitignore now

**Comment by Nyxchrono** [comment]
![wooo-yeah-baby-gif](https://github.com/VisualError/Better-Lobbies/assets/154691752/ccc28916-ceb2-4555-b79d-75fe371c46d2)
