### ISSUE TITLE
[Feature Request] New Menu/Replace the Invite Friends with lobby code

### ISSUE THREAD

**Issue by CatsArmy** [VisualError/Better-Lobbies#8]
maybe make it show to code somewhere in the steam menu or something or open another lil menu/popup that lets you select which one you want

reasoning is this damn overlapping: 
![image](https://github.com/VisualError/Better-Lobbies/assets/104517593/ca827d51-7534-45ce-ae8c-fa6a3543f5e4)

**Comment by CatsArmy** [comment]
So ima just take that as a no

**Comment by VisualError** [comment]
I'll get into this eventually

**Comment by VisualError** [comment]
Should be fixed in the 2.0.1 release
